# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  dockerId: my-docker-id  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: my-image-name  # Replace with the name of the image you want to publish

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
    displayName: 'Run a one-line script lin'
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: echo hello from macOS
    displayName: 'Run a one-line script mac'
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      echo hello from win
      echo helloe from win line two
      cmake --version
      git --version
      docker --version

    displayName: 'Run a two-line script msw'
- job: KiCad_Winbuilder_x86_64
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      git clone https://github.com/KiCad/kicad-winbuilder.git
      cd kicad-winbuilder
      set
      echo Yoyoyoyoy
      cmake --version
      REM make_x86_64.bat
    displayName: 'Attempting to build kicad-winbuilder'

- job: KiCad_Winbuilder_i686
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      git clone https://github.com/KiCad/kicad-winbuilder.git
      cd kicad-winbuilder
      set
      echo Yoyoyoyoy
      cmake --version
      REM make_i686.bat
    displayName: 'Attempting to build kicad-winbuilder'
